import React from "react";
import Dropdown from "./Dropdown";

const ports = [
  { name: "Antwerpen", code: "BEANR" },
  { name: "Blankenberge", code: "BEBBG" },
  { name: "Boekhoute", code: "BEBHE" },
  { name: "Kieldrecht", code: "BEKDE" },
  { name: "Nieuwpoort", code: "BENIE" },
  { name: "Oostende (Ostend)", code: "BEOST" },
  { name: "Zeebrugge", code: "BEZEE" },
  { name: "Akhtopol", code: "BGAKH" },
  { name: "Balchik", code: "BGBAL" },
  { name: "Burgas", code: "BGBOJ" },
  { name: "Byala", code: "BGBYL" },
  { name: "Klaipeda", code: "LTKLJ" },
  { name: "Neringa", code: "LTNID" },
  { name: "Palanga", code: "LTPLQ" },
  { name: "Sturk\u00f6", code: "SESUO" },
  { name: "S\u00e4v\u00f6", code: "SESV2" },
  { name: "Sv\u00e4lte", code: "SESV3" },
  { name: "Svanhalla", code: "SESVH" },
  { name: "Svanshall", code: "SESVL" },
  { name: "S\u00e4ivisn\u00e4s", code: "SESVS" },
  { name: "Svart\u00f6", code: "SESVT" },
  { name: "Stavsudda", code: "SESVU" },
  { name: "Sysne", code: "SESYE" },
  { name: "Syd-Koster", code: "SESYK" },
  { name: "Styrsvik", code: "SESYV" },
  { name: "H\u00f6llviken", code: "SESZI" },
  { name: "T\u00e4fte\u00e5", code: "SETAF" },
  { name: "Tallsk\u00e4r", code: "SETAL" },
  { name: "T\u00e5rterviken", code: "SETAR" },
  { name: "Tjock\u00f6", code: "SETCK" },
  { name: "Tegelstrand", code: "SETGL" },
  { name: "Tj\u00e4rn\u00f6", code: "SETJA" },
  { name: "Tj\u00f6rnekalv", code: "SETJK" },
  { name: "Tjurk\u00f6, Karlskrona", code: "SETJR" },
  { name: "Tjuvkil", code: "SETJU" },
  { name: "Torkelstorp", code: "SETKT" },
  { name: "Timmernabben", code: "SETMM" },
  { name: "Tr\u00e4nn\u00f6", code: "SETNN" },
  { name: "Torhamn", code: "SETOH" },
  { name: "Torr\u00f6", code: "SETOO" },
  { name: "Torekov", code: "SETOV" },
  { name: "Tor\u00f6", code: "SETR2" },
  { name: "Tr\u00e4sl\u00f6vsl\u00e4ge", code: "SETRE" },
  { name: "Trelleborg", code: "SETRG" },
  { name: "Trollharen", code: "SETRH" },
  { name: "Torslanda", code: "SETRL" },
  { name: "Trensum", code: "SETRM" },
  { name: "T\u00e4rn\u00f6", code: "SETRN" },
  { name: "Trolleboda", code: "SETRO" },
  { name: "Trosa", code: "SETRS" },
  { name: "Trund\u00f6n", code: "SETRU" },
  { name: "Trysunda", code: "SETRY" },
  { name: "Tors\u00f6", code: "SETSO" },
  { name: "Tumlehed", code: "SETUH" },
  { name: "Tystberga", code: "SETYA" },
  { name: "Tynder\u00f6", code: "SETYD" },
  { name: "Tyrisl\u00f6t", code: "SETYT" },
  { name: "Uddevalla", code: "SEUDD" },
  { name: "Ugglarp", code: "SEUGG" },
  { name: "Ulebergshamn", code: "SEUGN" },
  { name: "Ulv\u00f6hamn", code: "SEULH" },
  { name: "Ultr\u00e5", code: "SEULT" },
  { name: "Ume\u00e5", code: "SEUME" },
  { name: "Unnestads L\u00e4ge", code: "SEUNL" },
  { name: "Ungsk\u00e4r", code: "SEUNR" },
  { name: "Upplandsbodarna", code: "SEUPB" },
  { name: "Stenshamn, Utl\u00e4ngan", code: "SEUTL" },
  { name: "Utklippan", code: "SEUTN" },
  { name: "Ut\u00f6", code: "SEUTO" },
  { name: "Uttorp, Sturk\u00f6", code: "SEUTS" },
  { name: "Utvaln\u00e4s", code: "SEUTV" },
  { name: "Uvmar\u00f6 Hamn", code: "SEUVH" },
  { name: "V\u00e4stbacken", code: "SEVAB" },
  { name: "Valje", code: "SEVAE" },
  { name: "Varberg", code: "SEVAG" },
  { name: "Valdemarsvik", code: "SEVAK" },
  { name: "Vallvik", code: "SEVAL" },
  { name: "V\u00e5tn\u00e4s", code: "SEVAT" },
  { name: "V\u00e5nevik", code: "SEVAV" },
  { name: "Visby", code: "SEVBY" },
  { name: "V\u00e4ndburg", code: "SEVDB" },
  { name: "Vedhall", code: "SEVDH" },
  { name: "V\u00e4dersk\u00e4r", code: "SEVDK" },
  { name: "Vegeholm", code: "SEVEH" },
  { name: "Vejbystrand", code: "SEVEJ" },
  { name: "Vellinge", code: "SEVEL" },
  { name: "Viken, Tanum", code: "SEVEN" },
  { name: "V\u00e4stra Ekn\u00f6", code: "SEVEO" },
  { name: "Vr\u00e5ng\u00f6", code: "SEVGO" },
  { name: "Vagnh\u00e4rad", code: "SEVHD" },
  { name: "Vinbr\u00e4cka", code: "SEVIB" },
  { name: "Videbergshamn", code: "SEVID" },
  { name: "Villinge", code: "SEVIE" },
  { name: "Vikh\u00f6g", code: "SEVIH" },
  { name: "Valje, S\u00f6lvesborg", code: "SEVJE" },
  { name: "V\u00e4jern", code: "SEVJR" },
  { name: "Vik", code: "SEVK2" },
  { name: "Verk\u00f6, Karlskrona", code: "SEVKA" },
  { name: "Karlshamn-V\u00e4gga", code: "SEVKL" },
  { name: "Viken, H\u00f6gan\u00e4s", code: "SEVKN" },
  { name: "Vallda", code: "SEVLD" },
  { name: "V\u00e5ll\u00f6", code: "SEVLO" },
  { name: "V\u00e4rnan\u00e4s", code: "SEVNN" },
  { name: "Vin\u00f6", code: "SEVNO" },
  { name: "V\u00e4stra N\u00e4s", code: "SEVSN" },
  { name: "V\u00e4ns\u00f6", code: "SEVSO" },
  { name: "V\u00e4stergarn", code: "SEVSR" },
  { name: "Vitem\u00f6lla", code: "SEVTM" },
  { name: "V\u00e4stern\u00e4s", code: "SEVTN" },
  { name: "V\u00e4t\u00f6", code: "SEVTO" },
  { name: "Vitsgarn", code: "SEVTS" },
  { name: "V\u00e4stervik", code: "SEVVK" },
  { name: "Vaxholm", code: "SEVXH" },
  { name: "Wallhamn", code: "SEWAL" },
  { name: "Yngsj\u00f6", code: "SEYNG" },
  { name: "Ystad", code: "SEYST" },
  { name: "Ytterby", code: "SEYTB" },
  { name: "Yttervik", code: "SEYTK" },
  { name: "Ytter\u00f6n", code: "SEYTO" },
  { name: "Yxlan", code: "SEYXN" },
  { name: "Yxl\u00f6", code: "SEYXO" },
];

function PortsDropdown({ formControl, registerName }) {

  return (
    <Dropdown
      options={ports}
      formControl={formControl}
      registerName={registerName}
    />
  );
}

export default PortsDropdown;
