import React from "react";
import Dropdown from "./Dropdown";

const species = [
  { name: "Adriatic sturgeon", code: "AAA" },
  { name: "Twobar seabream", code: "AAB" },
  { name: "Bowfin", code: "AAC" },
  { name: "Yangtze sturgeon", code: "AAD" },
  { name: "Tailjet frogfish", code: "AAE" },
  { name: "Lake sturgeon", code: "AAF" },
  { name: "Indian mottled eel", code: "AAG" },
  { name: "Amur sturgeon", code: "AAH" },
  { name: "Chinese sturgeon", code: "AAI" },
  { name: "African longfin eel", code: "AAJ" },

  { name: "Blue ling", code: "BLI" },
  { name: "Verany's enope squid", code: "BLJ" },
  { name: "Brill", code: "BLL" },
  { name: "Black marlin", code: "BLM" },
  { name: "Pugheaded pipefish", code: "BLN" },
  { name: "Trout barb", code: "BLO" },
  { name: "Patagonian blennie", code: "BLP" },
  { name: "White-eye goby", code: "BLQ" },
  { name: "Blacktip reef shark", code: "BLR" },
  { name: "Anadara clams nei", code: "BLS" },
  { name: "Bullet tuna", code: "BLT" },
  { name: "Bluefish", code: "BLU" },
  { name: "Queen triggerfish", code: "BLV" },
  { name: "Blue whale", code: "BLW" },
  { name: "Ballia", code: "BLX" },
  { name: "Shortfin searobin", code: "BLY" },
  { name: "Antenna codlet", code: "BMA" },
  { name: "Gangetic mystus", code: "BMC" },
  { name: "Mediterranean spiderfish", code: "BME" },
  { name: "Alaskan ronquil", code: "BMF" },
  { name: "Long whiskers catfish", code: "BMG" },
  { name: "Hilda's grunter", code: "BMH" },
  { name: "Green humphead parrotfish", code: "BMK" },
  { name: "Slim flounder", code: "BML" },
  { name: "Twospot catfish", code: "BMM" },
  { name: "Blue moki", code: "BMO" },
  { name: "Greenstreaked eartheater", code: "BMP" },
  { name: "Duckbill flathead", code: "BMQ" },
  { name: "Murray's skate", code: "BMU" },
  { name: "Striped dwarf catfish", code: "BMV" },
  { name: "Clown loach", code: "BMW" },
  { name: "Yellowtail bass", code: "BMX" },
  { name: "Bowhead whale", code: "BMY" },
  { name: "Orangefin tetra", code: "BNA" },
  { name: "Tricolor sharkminnow", code: "BNB" },
  { name: "Longfin bonefish", code: "BNF" },
  { name: "Halfround cardita", code: "BNG" },
  { name: "Throat-spine gudgeon", code: "BNJ" },
  { name: "Spiny mole crab", code: "BNK" },
  { name: "Mourning tetra", code: "BNP" },
  { name: "Peppermint swimcrab", code: "BNQ" },
  { name: "Smallfin lanternfish", code: "BNS" },
  { name: "Pearleyes nei", code: "BNT" },
  { name: "Machaca", code: "BNV" },
  { name: "Longman's beaked whale", code: "BNW" },
  { name: "Bonga shad", code: "BOA" },
  { name: "Atlantic seabob", code: "BOB" },
  { name: "Boarfish", code: "BOC" },
  { name: "Bengal loach", code: "BOD" },
  { name: "Black oreo", code: "BOE" },
  { name: "Bonefish", code: "BOF" },
  { name: "Bogue", code: "BOG" },
  { name: "Tiger loach", code: "BOH" },
  { name: "Fransmadam", code: "BOJ" },
  { name: "Cochu's blue tetra", code: "BOK" },
  { name: "Boeseman croaker", code: "BOM" },
  { name: "Atlantic bonito", code: "BON" },
  { name: "Plain bonito", code: "BOP" },
  { name: "Horned murex", code: "BOQ" },
  { name: "Boarfishes nei", code: "BOR" },
  { name: "Pacific seabobs", code: "BOS" },
  { name: "Boto", code: "BOT" },
  { name: "Gulf toadfish", code: "BOU" },
  { name: "Northern bottlenose whale", code: "BOW" },
  { name: "Purple dye murex", code: "BOY" },
  { name: "Atlantic fanfish", code: "BPB" },
  { name: "Guitarrita", code: "BPC" },
  { name: "Guinean toadfish", code: "BPE" },
  { name: "Kumakuma", code: "BPF" },
  { name: "Abyssal spiderfish", code: "BPG" },
  { name: "Arrowhead soapfish", code: "BPH" },
  { name: "Blotched picarel", code: "BPI" },
  { name: "Zebra catfish", code: "BPJ" },
  { name: "Polar bear", code: "BPL" },
  { name: "Camouflaged catfish", code: "BPM" },
  { name: "Ecuador banjo catfish", code: "BPN" },
  { name: "Pacific pomfret", code: "BPQ" },
  { name: "Purple brotula", code: "BPS" },
  { name: "Laulao catfish", code: "BPT" },
  { name: "Pigmy beaked whale", code: "BPW" },
  { name: "Prickly fanfish", code: "BPY" },
  { name: "Brent goose", code: "BPZ" },
  { name: "Common spider conch", code: "BQA" },
  { name: "Hairy ark", code: "BQB" },
  { name: "Bottlebrush crayfish", code: "BQC" },
  { name: "Dilate piddock", code: "BQD" },
  { name: "Fly spotted auger", code: "BQE" },
  { name: "Decussate ark", code: "BQF" },
  { name: "Chiragra spider conch", code: "BQH" },
  { name: "Milleped spider conch", code: "BQI" },
  { name: "Scorpio spider conch", code: "BQJ" },
  { name: "Marlinspike", code: "BQK" },
  { name: "Coconut crab", code: "BQL" },
  { name: "Manila piddock", code: "BQM" },
  { name: "Giant spider conch", code: "BQN" },
  { name: "Striated buccinum", code: "BQO" },
  { name: "Ornate arm squid", code: "BQP" },
  { name: "Subulate auger", code: "BQQ" },
  { name: "Common arm squid", code: "BQR" },
  { name: "Pacific mud piddock", code: "BQS" },
  { name: "Truncate barnea", code: "BQT" },
  { name: "Almond ark", code: "BQU" },
  { name: "Canada goose", code: "BQV" },
  { name: "Orange spider conch", code: "BQW" },
  { name: "Butterfishes nei", code: "BQX" },
  { name: "Dragonfishes nei", code: "BQY" },
  { name: "Barnacle goose", code: "BQZ" },
  { name: "Black seabream", code: "BRB" },
  { name: "Arm squids nei", code: "BRC" },
  { name: "Bearded brotula", code: "BRD" },
  { name: "Blackbelly rosefish", code: "BRF" },
  { name: "Barred grunt", code: "BRG" },
  { name: "Bristlemouths", code: "BRI" },
  { name: "Broadbodied toadfish", code: "BRK" },
  { name: "Copper shark", code: "BRO" },
  { name: "Burmeister's porpoise", code: "BRP" },
  { name: "Serra Spanish mackerel", code: "BRS" },
  { name: "Snaggletooth", code: "BRT" },
  { name: "Southern rays bream", code: "BRU" },
  { name: "Bryde's whale", code: "BRW" },
  { name: "Alfonsinos, etc. nei", code: "BRX" },
  { name: "Pomfrets, ocean breams nei", code: "BRZ" },
  { name: "Atlantic seabasses", code: "BSA" },
  { name: "Black seabass", code: "BSB" },
  { name: "Bluespotted seabream", code: "BSC" },
  { name: "Seabasses nei", code: "BSE" },
  { name: "Black scabbardfish", code: "BSF" },
  { name: "Blue shark", code: "BSH" },
  { name: "Basking shark", code: "BSK" },
  { name: "Andalusian barbel", code: "BSL" },
  { name: "Papermouth", code: "BSM" },
  { name: "Slender barb", code: "BSN" },
  { name: "Warehou nei", code: "BSP" },
  { name: "Musical furry lobster", code: "BSQ" },
  { name: "Brazilian sardinella", code: "BSR" },
  { name: "European seabass", code: "BSS" },
  { name: "Threespot barb", code: "BST" },
  { name: "Sherpherd's beaked whale", code: "BSW" },
  { name: "Groupers, seabasses nei", code: "BSX" },
  { name: "High-finned glass perchlet", code: "BSY" },
  { name: "Argentine seabass", code: "BSZ" },
  { name: "Stone loach", code: "BTB" },
  { name: "Batfish", code: "BTF" },
  { name: "Gulf butterfishes nei", code: "BTG" },
  { name: "Bigeye thresher", code: "BTH" },
  { name: "Bighead sculpin", code: "BTJ" },
  { name: "Cano toadfish", code: "BTM" },
  { name: "Mottled loach", code: "BTO" },
  { name: "January octopus", code: "BTQ" },
  { name: "Hound needlefish", code: "BTS" },
  { name: "True's beaked whale", code: "BTW" },
  { name: "Blacksmelts", code: "BTY" },
  { name: "Atlantic bumper", code: "BUA" },
  { name: "Bigmouth buffalo", code: "BUB" },
  { name: "Bombay-duck", code: "BUC" },
  { name: "Mediterranean barbel", code: "BUD" },
  { name: "Buffalofishes nei", code: "BUF" },
  { name: "Broadband barb", code: "BUI" },
  { name: "Butterfly kingfish", code: "BUK" },
  { name: "Line-spotted barb", code: "BUL" },
  { name: "Blue marlin", code: "BUM" },
  { name: "Spotscale barb", code: "BUO" },
  { name: "Pacific rudderfish", code: "BUP" },
  { name: "Largescale yellowfish", code: "BUQ" },
  { name: "Sompat grunt", code: "BUR" },
  { name: "Butterflyfishes", code: "BUS" },
  { name: "Atlantic butterfish", code: "BUT" },
  { name: "Straightfin barb", code: "BUU" },
  { name: "Hubbs' beaked whale", code: "BUW" },
  { name: "Butterfishes, pomfrets nei", code: "BUX" },

  { name: "Slender frostfish", code: "BWN" },
  { name: "Ghost moray", code: "BWO" },
  { name: "Boobies nei", code: "BWR" },
  { name: "Four-eyed sleeper", code: "BWS" },
  { name: "Mangrove horseshoe crab", code: "BWU" },
  { name: "Sowerby's beaked whale", code: "BWW" },
  { name: "Top minnow", code: "BXB" },
  { name: "Alfonsino", code: "BXD" },
  { name: "Boxfishes nei", code: "BXF" },
  { name: "Frigates, man of war nei", code: "BXJ" },
  { name: "Omura\u2019s whale", code: "BXO" },
  { name: "Marlins nei", code: "BXQ" },
  { name: "Herons nei", code: "BXR" },
  { name: "Spade-toothed whale", code: "BXT" },
  { name: "Jaegers nei", code: "BXU" },
  { name: "Korean stumpy bullhead", code: "BXW" },
  { name: "Pink pipefish", code: "BXY" },
  { name: "Aleutian skate", code: "BYA" },
  { name: "Silver perch", code: "BYB" },
  { name: "Dark-belly skate", code: "BYE" },
  { name: "Alaska skate", code: "BYF" },
  { name: "Sandpaper skate", code: "BYI" },
  { name: "Flathead skate", code: "BYJ" },
  { name: "Commander skate", code: "BYL" },
  { name: "Pale ray", code: "BYP" },
  { name: "Richardson's ray", code: "BYQ" },
  { name: "Kerguelen sandpaper skate", code: "BYR" },
  { name: "Splendid alfonsino", code: "BYS" },
  { name: "Longnose deep-sea skate", code: "BYU" },
  { name: "Gray's beaked whale", code: "BYW" },
  { name: "Deep-sea skate", code: "BYY" },
  { name: "Broadnose skate", code: "BZB" },
  { name: "Nurse tetra", code: "BZC" },
  { name: "Blackbar hogfish", code: "BZD" },
  { name: "Tropicbirds nei", code: "BZF" },
  { name: "Tiete tetra", code: "BZI" },
  { name: "Pearly prickleback", code: "BZJ" },
  { name: "Narrowhead catshark", code: "BZL" },
  { name: "Patagonian skate", code: "BZM" },
  { name: "Bryozoans", code: "BZN" },
  { name: "Bach\u2019s catshark", code: "BZO" },
  { name: "Pelicans nei", code: "BZP" },
  { name: "Cuphead skate", code: "BZS" },
  { name: "Western Australia pigfish", code: "BZV" },
  { name: "Bonitos nei", code: "BZX" },
  { name: "Daisy midshipman", code: "BZY" },
  { name: "Deraniyagala's beaked whale", code: "BZZ" },
  { name: "Atlantic wolffish", code: "CAA" },
  { name: "Northern wolffish", code: "CAB" },
  { name: "Squarehead catfish", code: "CAC" },
  { name: "Jonah crabs, rock crabs nei", code: "CAD" },
  { name: "Eeltail catfishes", code: "CAE" },
  { name: "Catfishes nei", code: "CAF" },
  { name: "Glass catfishes", code: "CAG" },
  { name: "Elephantfishes, etc. nei", code: "CAH" },
  { name: "Spectacled caiman", code: "CAI" },
  { name: "Angler catfish", code: "CAK" },
  { name: "Callinectes swimcrabs nei", code: "CAL" },
  { name: "South polar skua", code: "CAM" },
  { name: "Naked catfishes", code: "CAN" },
  { name: "Spotted catfish", code: "CAO" },
  { name: "Capelin", code: "CAP" },
  { name: "Brown skua", code: "CAQ" },
  { name: "Cartilaginous fishes nei", code: "CAR" },
  { name: "Spotted wolffish", code: "CAS" },
  { name: "Wolffishes(=Catfishes) nei", code: "CAT" },
  { name: "Caulerpa seaweeds", code: "CAU" },
  { name: "Comet", code: "CAW" },
  { name: "Sea catfishes nei", code: "CAX" },
  { name: "Sharpnose sculpin", code: "CAZ" },
  { name: "Cobia", code: "CBA" },
  { name: "Beach silverside", code: "CBB" },
  { name: "Red bandfish", code: "CBC" },
  { name: "Jolthead porgy", code: "CBD" },
  { name: "Crocodile fish", code: "CBF" },
  { name: "Driftfish", code: "CBG" },
  { name: "Mangrove hermit crab", code: "CBI" },
  { name: "Short-bodied pipefish", code: "CBJ" },
  { name: "Dogtooth herring", code: "CBK" },
  { name: "Brown meagre", code: "CBM" },
  { name: "Kroyer's deep-sea angler fish", code: "CBO" },
  { name: "Eel catfish", code: "CBP" },
  { name: "Chestnut goby", code: "CBQ" },
  { name: "Comber", code: "CBR" },
  { name: "Maputo conger", code: "CBS" },
  { name: "Philippine catfish", code: "CBT" },
  { name: "Silver tetra", code: "CBU" },
  { name: "Longnose conger", code: "CBW" },
  { name: "Argentine pearlfish", code: "CBY" },
  { name: "Blue flounder", code: "CBZ" },
  { name: "Bignose shark", code: "CCA" },
  { name: "Spinner shark", code: "CCB" },
  { name: "Nervous shark", code: "CCC" },
  { name: "Whitecheek shark", code: "CCD" },
  { name: "Bull shark", code: "CCE" },
  { name: "Pigeye shark", code: "CCF" },
  { name: "Galapagos shark", code: "CCG" },
  { name: "Blackspot shark", code: "CCI" },
  { name: "Pondicherry shark", code: "CCK" },
  { name: "Blacktip shark", code: "CCL" },
  { name: "Hardnose shark", code: "CCM" },
  { name: "Blacknose shark", code: "CCN" },
  { name: "Finetooth shark", code: "CCO" },
  { name: "Sandbar shark", code: "CCP" },
  { name: "Spottail shark", code: "CCQ" },
  { name: "Smalltail shark", code: "CCR" },
  { name: "Night shark", code: "CCS" },
  { name: "Sand tiger shark", code: "CCT" },
  { name: "Australian blacktip shark", code: "CCU" },
  { name: "Caribbean reef shark", code: "CCV" },
  { name: "Blacktail reef shark", code: "CCW" },
  { name: "Borneo shark", code: "CCX" },
  { name: "Graceful shark", code: "CCY" },
  { name: "Creek whaler", code: "CCZ" },
  { name: "Threadfin shad", code: "CDA" },
  { name: "Nosey dottyback", code: "CDB" },
  { name: "Porae", code: "CDD" },
  { name: "Midway deep-sea coral", code: "CDE" },
  { name: "Darter characin", code: "CDF" },
  { name: "Cory's shearwater", code: "CDI" },
  { name: "Roundbelly pellonuline", code: "CDK" },
  { name: "Cardinal fishes nei", code: "CDL" },
  { name: "Day's round herring", code: "CDM" },
  { name: "Sloane's viperfish", code: "CDN" },
  { name: "River carpsucker", code: "CDO" },
  { name: "Estuarine crocodile", code: "CDP" },
  { name: "Keeled mud lobster", code: "CDQ" },
  { name: "Trident grenadier", code: "CDR" },
  { name: "Siamese crocodile", code: "CDS" },
  { name: "Yabby crayfish", code: "CDT" },
  { name: "Highfin coralfish", code: "CDV" },
  { name: "Burmese spineless eel", code: "CDW" },
  { name: "Croakers, drums nei", code: "CDX" },
  { name: "Northern cods nei", code: "CDZ" },
  { name: "Needle dogfish", code: "CEA" },
  { name: "Short-headed sculpin", code: "CEB" },
  { name: "West African ladyfish", code: "CEC" },
  { name: "Mosaic gulper shark", code: "CEE" },
  { name: "Malabar sprat", code: "CEF" },
  { name: "Senegalese ladyfish", code: "CEG" },
  { name: "Marini's grenadier", code: "CEH" },
  { name: "Pacific ladyfish", code: "CEI" },
  { name: "Crocodile flathead", code: "CEJ" },
  { name: "Taiwan gulper shark", code: "CEK" },
  { name: "Momo, boke magai, misu coral", code: "CEL" },
  { name: "Smallfin gulper shark", code: "CEM" },
  { name: "Ruffs, barrelfishes nei", code: "CEN" },
  { name: "Rudderfish", code: "CEO" },
  { name: "Cephalopods nei", code: "CEP" },
  { name: "Cero", code: "CER" },
  { name: "Pike icefish", code: "CES" },
  { name: "Wedge sole", code: "CET" },
  { name: "Dumb gulper shark", code: "CEU" },

  { name: "Bluespotted hind", code: "CFY" },
  { name: "Golden hind", code: "CFZ" },
  { name: "Ganges shark", code: "CGA" },
  { name: "Goldstripe characin", code: "CGB" },
  { name: "Burmese river gizzard shad", code: "CGD" },
  { name: "West African geryon", code: "CGE" },
  { name: "Japanese sand shrimp", code: "CGF" },
  { name: "Speartooth shark", code: "CGG" },
  { name: "Indian river shad", code: "CGH" },
  { name: "Ganges River gizzard shad", code: "CGI" },
  { name: "Lizard triplefin", code: "CGJ" },
  { name: "Gale's pipefish", code: "CGL" },
  { name: "Africa-bighead catfish, hybrid", code: "CGM" },
  { name: "Goldfish", code: "CGO" },
  { name: "Gilchrist's round herring", code: "CGR" },
  { name: "Smoothbelly pellonuline", code: "CGS" },
  { name: "Redspotted tetra", code: "CGT" },
  { name: "Whitespotted garden eel", code: "CGU" },
  { name: "Evermann's conger", code: "CGV" },
  { name: "Carangids nei", code: "CGX" },
  { name: "Gabon gurnard", code: "CGY" },
  { name: "Conger eels nei", code: "CGZ" },
  { name: "Characins nei", code: "CHA" },
  { name: "Ghost shark", code: "CHB" },
  { name: "Choro mussel", code: "CHC" },
  { name: "Black dolphin", code: "CHD" },
  { name: "Masu(=Cherry) salmon", code: "CHE" },
  { name: "Mandarin dogfish", code: "CHF" },
  { name: "Chacunda gizzard shad", code: "CHG" },
  { name: "Mexican mojarra", code: "CHH" },
  { name: "Chinook(=Spring=King) salmon", code: "CHI" },
  { name: "Plownose chimaera", code: "CHJ" },
  { name: "Blackbelt cichlid", code: "CHK" },
  { name: "Jaguar guapote", code: "CHL" },
  { name: "Cape elephantfish", code: "CHM" },
  { name: "Cape Hope squid", code: "CHO" },
  { name: "South American pilchard", code: "CHP" },
  { name: "Chocolate rockshell", code: "CHQ" },
  { name: "Chars nei", code: "CHR" },
  { name: "Chilean nylon shrimp", code: "CHS" },
  { name: "Chum(=Keta=Dog) salmon", code: "CHU" },
  { name: "Purple chimaera", code: "CHV" },
  { name: "Cichlasoma nei", code: "CHX" },
  { name: "Chinese seerfish", code: "CHY" },
  { name: "Roughskin spurdog", code: "CHZ" },
  { name: "Arctic cisco", code: "CIA" },
  { name: "Valaam whitefish", code: "CIB" },
  { name: "Khadary-whitefish", code: "CIC" },
  { name: "Sawtooth caridina", code: "CID" },
  { name: "Cinnamon flounder", code: "CIF" },
  { name: "Peled", code: "CIJ" },
  { name: "Kiyi", code: "CIK" },
  { name: "Spotted flounder", code: "CIL" },
  { name: "Mouthbrooding cichlids", code: "CIM" },
  { name: "Muksun", code: "CIN" },
  { name: "Daggernose shark", code: "CIO" },
  { name: "Irish pollan", code: "CIP" },
  { name: "Broad whitefish", code: "CIQ" },
  { name: "Lake cisco", code: "CIS" },
  { name: "Citharids nei", code: "CIT" },
  { name: "Tugun", code: "CIU" },
  { name: "Citharinus nei", code: "CIV" },
  { name: "Sardine cisco", code: "CIW" },
  { name: "Cichlids nei", code: "CIX" },
  { name: "Bloater", code: "CIY" },
  { name: "Shortnose cisco", code: "CIZ" },
  { name: "Cuban legskate", code: "CJA" },
  { name: "Blue and gold fusilier", code: "CJC" },
  { name: "Smoothnose legskate", code: "CJD" },
  { name: "Girdled wrasse", code: "CJE" },
  { name: "Oceanian crayfishes nei", code: "CJF" },
  { name: "S\u00f4hachi", code: "CJJ" },
  { name: "Dwarf round herring", code: "CJL" },
  { name: "Chilean jack mackerel", code: "CJM" },
  { name: "Longfinned bullseye", code: "CJN" },
  { name: "Roughnose legskate", code: "CJP" },
  { name: "Tule bulrush", code: "CJQ" },
  { name: "Pink flabby whalefish", code: "CJR" },
  { name: "Florida round herring", code: "CJS" },
  { name: "Triangular legskate", code: "CJT" },
  { name: "Redbelly yellowtail fusilier", code: "CJU" },
  { name: "Variable-lined fusilier", code: "CJV" },
  { name: "Tule nei", code: "CJW" },
  { name: "Fusiliers nei", code: "CJX" },
  { name: "Lunar fusilier", code: "CJZ" },
  { name: "Atlantic croaker", code: "CKA" },
  { name: "Globosehead rattail", code: "CKC" },
  { name: "Unicorn grenadier", code: "CKD" },
  { name: "Pacific grenadier", code: "CKE" },
  { name: "Carmine grenadier", code: "CKF" },
  { name: "Amami grenadier", code: "CKG" },
  { name: "Abyssal grenadier", code: "CKH" },
  { name: "Araucanian herring", code: "CKI" },
  { name: "Popeye grenadier", code: "CKJ" },
  { name: "Humboldt grenadier", code: "CKK" },
  { name: "Law croaker", code: "CKL" },
  { name: "Whitemouth croaker", code: "CKM" },
  { name: "Loosescale grenadier", code: "CKN" },
  { name: "Swordsnout grenadier", code: "CKO" },
  { name: "Pacific porgy", code: "CKQ" },
  { name: "Spiny grenadier", code: "CKR" },
  { name: "Shoulderspot grenadier", code: "CKS" },
  { name: "Kura shad", code: "CKT" },
  { name: "Spearnose grenadier", code: "CKU" },
  { name: "Hawknose grenadier", code: "CKV" },
  { name: "West African croakers nei", code: "CKW" },
  { name: "Firebelly grenadier", code: "CKX" },
  { name: "Argentine croaker", code: "CKY" },
  { name: "Atlantic goldeneye tilefish", code: "CKZ" },
  { name: "Black and Caspian Sea sprat", code: "CLA" },
  { name: "Atlantic surf clam", code: "CLB" },
  { name: "Coelacanth", code: "CLC" },
  { name: "Sliteye shark", code: "CLD" },
  { name: "Anchovy sprat", code: "CLE" },
  { name: "Freshwater clams nei", code: "CLF" },
  { name: "Southern Caspian sprat", code: "CLG" },
  { name: "Northern quahog(=Hard clam)", code: "CLH" },
  { name: "Lingcod", code: "CLI" },
  { name: "Japanese carpet shell", code: "CLJ" },
  { name: "Ganges River sprat", code: "CLK" },
  { name: "Barbeled houndshark", code: "CLL" },
  { name: "Macha clam", code: "CLM" },
  { name: "Mudfish", code: "CLN" },
  { name: "Peacock cichlid", code: "CLO" },
  { name: "Herrings, sardines nei", code: "CLP" },
  { name: "Ocean quahog", code: "CLQ" },
  { name: "Atl.jackknife(=Atl.razor clam)", code: "CLR" },
  { name: "Sand gaper", code: "CLS" },
  { name: "Stimpson's surf clam", code: "CLT" },
  { name: "Clupeoids nei", code: "CLU" },
  { name: "Venus clams nei", code: "CLV" },
  { name: "Clams, etc. nei", code: "CLX" },
  { name: "Longfin grenadier", code: "CLY" },
  { name: "North African catfish", code: "CLZ" },
  { name: "Asian clam", code: "CMA" },
  { name: "Cuban crocodile", code: "CMB" },
  { name: "Bighead catfish", code: "CMC" },
  { name: "Commerson's dolphin", code: "CMD" },
  { name: "Morelet's crocodile", code: "CME" },
  { name: "Farrer's scallop", code: "CMF" },
  { name: "Mrigal carp", code: "CMG" },
  { name: "Silver chimaera", code: "CMH" },
  { name: "Swordtail characin", code: "CMI" },
  { name: "Japanese corbicula", code: "CMJ" },
  { name: "Damselfish", code: "CMK" },
  { name: "Manila clam", code: "CMM" },
  { name: "Noble scallop", code: "CMN" },
  { name: "Rabbit fish", code: "CMO" },
  { name: "Spotted coral croucher", code: "CMQ" },
  { name: "Mediterranean shore crab", code: "CMR" },
  { name: "Saucereye porgy", code: "CMV" },
  { name: "Bobtail eel", code: "CMY" },
  { name: "Manefish", code: "CMZ" },
  { name: "Snakehead", code: "CNA" },
  { name: "Australian river gizzard shad", code: "CNE" },
  { name: "Australian lungfish", code: "CNF" },
  { name: "New Guinea crocodile", code: "CNG" },
  { name: "Cnidarians nei", code: "CNI" },
  { name: "Japanese gizzard shad", code: "CNJ" },
  { name: "G\u00fcnther's grenadier", code: "CNK" },
  { name: "Sailfin tetra", code: "CNL" },
  { name: "Cobbler", code: "CNM" },
  { name: "Sicklefin chimaera", code: "CNN" },
  { name: "Spotted snakehead", code: "CNP" },
  { name: "Lake Tumba dwarf sprat", code: "CNR" },
  { name: "Bloch's gizzard shad", code: "CNS" },
  { name: "Rough triggerfish", code: "CNT" },
  { name: "Whitefin wolf-herring", code: "CNU" },
  { name: "Whitenose shark", code: "CNX" },
  { name: "Crangon shrimps nei", code: "CNZ" },
  { name: "American conger", code: "COA" },
  { name: "Shi drum", code: "COB" },
  { name: "Common edible cockle", code: "COC" },
  { name: "Atlantic cod", code: "COD" },
  { name: "European conger", code: "COE" },
  { name: "Garnet coral", code: "COG" },
  { name: "Coho(=Silver) salmon", code: "COH" },
  { name: "Longfin African conger", code: "COI" },
  { name: "Aka coral", code: "COJ" },
  { name: "Shiro, white coral", code: "COK" },
  { name: "Sardinia coral", code: "COL" },
  { name: "Narrow-barred Spanish mackerel", code: "COM" },
  { name: "Stromboid conchs nei", code: "CON" },
  { name: "Queen conch", code: "COO" },
  { name: "Manytooth conger", code: "COQ" },
  { name: "Precious corals nei", code: "COR" },
  { name: "Argentine conger", code: "COS" },
  { name: "Galjoens nei", code: "COT" },
  { name: "Rainbow wrasse", code: "COU" },
  { name: "Navaga(=Wachna cod)", code: "COW" },
  { name: "Conger eels, etc. nei", code: "COX" },
  { name: "Cockles nei", code: "COZ" },
  { name: "Indian swellshark", code: "CPA" },
  { name: "Blotchy swell shark", code: "CPB" },
  { name: "Lollipop catshark", code: "CPC" },
  { name: "Harlequin catshark", code: "CPE" },
  { name: "Reticulated swellshark", code: "CPF" },
  { name: "Slender smooth-hound", code: "CPG" },
  { name: "Balloon shark", code: "CPH" },
  { name: "California pilchard", code: "CPI" },
  { name: "Delta silverside", code: "CPK" },
  { name: "Lowfin gulper shark", code: "CPL" },
  { name: "Pygmy right whale", code: "CPM" },
  { name: "Whitefinned swellshark", code: "CPN" },
  { name: "Chinese silver pomfret", code: "CPO" },
  { name: "Copper breams(=Hottentots) nei", code: "CPP" },
  { name: "Common prawn", code: "CPR" },
  { name: "Draughtsboard shark", code: "CPS" },
  { name: "Australian swellshark", code: "CPT" },
  { name: "Little gulper shark", code: "CPU" },
  { name: "Swellshark", code: "CPV" },
  { name: "Mexican grenadier", code: "CPX" },
  { name: "Graceful catshark", code: "CPY" },
  { name: "Snubnose pipefish", code: "CPZ" },
  { name: "Surgeon grenadier", code: "CQA" },
  { name: "Two-barred whiptail", code: "CQB" },
  { name: "Aconcagua grenadier", code: "CQC" },
  { name: "Filesnout grenadier", code: "CQD" },
  { name: "Shovelnose grenadier", code: "CQE" },
  { name: "Banded whiptail", code: "CQF" },
  { name: "Eyespot grenadier", code: "CQG" },
  { name: "Clearsnout grenadier", code: "CQH" },
  { name: "Blackfin grenadier", code: "CQI" },
  { name: "Japanese grenadier", code: "CQJ" },
  { name: "Kamohara grenadier", code: "CQK" },
  { name: "Hollowsnout grenadier", code: "CQL" },
  { name: "Formosa grenadier", code: "CQM" },
  { name: "Duckbill grenadier", code: "CQN" },
  { name: "Chilean grenadier", code: "CQO" },
  { name: "Longhead grenadier", code: "CQP" },
  { name: "Karrer's whiptail", code: "CQQ" },
  { name: "Silver whiptail", code: "CQR" },
  { name: "Rough-head whiptail", code: "CQS" },
  { name: "Notable whiptail", code: "CQT" },
  { name: "Javelin", code: "CQU" },
  { name: "Spearsnouted grenadier", code: "CQV" },
  { name: "Longarm grenadier", code: "CQW" },
  { name: "Six-band grenadier", code: "CQX" },
  { name: "Mugura grenadier", code: "CQY" },
  { name: "Roughback sculpin", code: "CQZ" },
  { name: "Marine crabs nei", code: "CRA" },
  { name: "Blue crab", code: "CRB" },
  { name: "Giant swimcrab", code: "CRC" },
  { name: "Danube crayfish", code: "CRD" },
  { name: "Edible crab", code: "CRE" },
  { name: "Blue trevally", code: "CRF" },
  { name: "Green crab", code: "CRG" },
  { name: "Australian crocodile", code: "CRH" },
  { name: "Nile crocodile", code: "CRI" },
  { name: "Jonah crab", code: "CRJ" },
  { name: "Atlantic rock crab", code: "CRK" },
  { name: "Blackmouth croaker", code: "CRL" },
  { name: "Crangonid shrimps nei", code: "CRN" },
  { name: "Crocodiles and alligators nei", code: "CRO" },
  { name: "Red claw crayfish", code: "CRP" },
  { name: "Queen crab", code: "CRQ" },
  { name: "Red crab", code: "CRR" },
  { name: "Portunus swimcrabs nei", code: "CRS" },
  { name: "Hairy marron crayfish", code: "CRT" },
  { name: "Marine crustaceans nei", code: "CRU" },
  { name: "Silver croaker", code: "CRV" },
  { name: "Palinurid spiny lobsters nei", code: "CRW" },
  { name: "Croakers nei", code: "CRX" },
  { name: "Yellow croaker", code: "CRY" },
  { name: "Dana swimcrab", code: "CRZ" },
  { name: "Hooded oyster", code: "CSC" },
  { name: "Pirapatinga", code: "CSD" },
  { name: "Angel skin coral", code: "CSE" },
  { name: "Longhead catshark", code: "CSF" },
  { name: "Common shrimp", code: "CSH" },
  { name: "Slipper cupped oyster", code: "CSI" },
  { name: "Japanese catshark", code: "CSJ" },
  { name: "Great skua", code: "CSK" },
  { name: "California sea lion", code: "CSL" },
  { name: "Cachama", code: "CSM" },
  { name: "Brown catshark", code: "CSN" },
  { name: "Pacu", code: "CSO" },
  { name: "Crystal shrimp", code: "CSP" },
  { name: "Hoary catshark", code: "CSQ" },
  { name: "Bagrid catfish", code: "CSR" },
  { name: "Hard corals, madrepores nei", code: "CSS" },
  { name: "Black catfishes nei", code: "CST" },
  { name: "Atlantic ghost catshark", code: "CSU" },
  { name: "Broadgill catshark", code: "CSV" },
  { name: "Longfin catshark", code: "CSW" },
  { name: "Flathead catshark", code: "CSX" },
  { name: "Upsidedown catfishes", code: "CSY" },
  { name: "Longnose catshark", code: "CSZ" },
  { name: "Castaneta", code: "CTA" },
  { name: "Common two-banded seabream", code: "CTB" },
  { name: "Common cuttlefish", code: "CTC" },
  { name: "Sharptooth smooth-hound", code: "CTD" },
  { name: "Spotless smooth-hound", code: "CTE" },
  { name: "Striped smooth-hound", code: "CTF" },
  { name: "Grooved carpet shell", code: "CTG" },
  { name: "Chilean skua", code: "CTH" },
  { name: "Dusky smooth-hound", code: "CTI" },
  { name: "Smalleye smooth-hound", code: "CTJ" },
  { name: "Brown smooth-hound", code: "CTK" },
  { name: "Cuttlefish, bobtail squids nei", code: "CTL" },
  { name: "Suckers nei", code: "CTM" },
  { name: "Grey smooth-hound", code: "CTN" },
  { name: "Torpedo-shaped catfishes nei", code: "CTO" },
  { name: "Triplewart seadevil", code: "CTQ" },
  { name: "Dwarf bobtail squid", code: "CTR" },
  { name: "Catla", code: "CTT" },
  { name: "Gummy shark", code: "CTU" },
  { name: "Axelrod's rainbowfish", code: "CTX" },
  { name: "Streaked gurnard", code: "CTZ" },
  { name: "Alabama shad", code: "CUA" },
  { name: "Black cusk-eel", code: "CUB" },
  { name: "Red cusk-eel", code: "CUC" },
  { name: "Dana viperfish", code: "CUD" },
  { name: "Caspian anadromous shad", code: "CUE" },
  { name: "Congo blind barb", code: "CUG" },
  { name: "Agrakhan shad", code: "CUH" },
  { name: "Caspian shad", code: "CUI" },
  { name: "Japanese sea cucumber", code: "CUJ" },
  { name: "Caspian marine shad", code: "CUK" },
  { name: "Slender conger", code: "CUL" },
  { name: "Nigerian fangtooth pellonuline", code: "CUM" },
  { name: "Cunner", code: "CUN" },
  { name: "Borneo River sprat", code: "CUO" },
  { name: "Banded yellowfish", code: "CUQ" },
  { name: "Thai river sprat", code: "CUR" },
  { name: "Pink cusk-eel", code: "CUS" },
  { name: "Hairtails, scabbardfishes nei", code: "CUT" },
  { name: "Saposhnikovi shad", code: "CUV" },
  { name: "Smooth razorfish", code: "CUW" },
  { name: "Sea cucumbers nei", code: "CUX" },
  { name: "Ansorge fangtooth pellonuline", code: "CUY" },
  { name: "Brook stickleback", code: "CUZ" },
  { name: "Sakhalin sculpin", code: "CVA" },
  { name: "Tanner crab", code: "CVB" },
  { name: "Chilean frog", code: "CVC" },
  { name: "Pencil urchins", code: "CVD" },
  { name: "Couma sea catfish", code: "CVE" },
  { name: "Monkeyface prickleback", code: "CVI" },
  { name: "Crevalle jack", code: "CVJ" },
  { name: "Chocolate hind", code: "CVK" },
  { name: "Sculptured shrimps nei", code: "CVL" },
  { name: "Black swallower", code: "CVN" },
  { name: "Arrow goby", code: "CVO" },
  { name: "Polar sculpin", code: "CVP" },
  { name: "Passany sea catfish", code: "CVQ" },
  { name: "Giant African cuttlefish", code: "CVT" },
  { name: "Sumatran river sprat", code: "CVU" },
  { name: "Common black-headed gull", code: "CVV" },
  { name: "Shortnose greeneye", code: "CVW" },
  { name: "Ground sharks", code: "CVX" },
  { name: "Grenadiers, whiptails nei", code: "CVY" },
  { name: "Potosi pupfish", code: "CVZ" },
  { name: "Black-Caspian Sea sprats nei", code: "CWA" },
  { name: "Swallow-tail", code: "CWB" },
  { name: "Karanteen seabream", code: "CWC" },
  { name: "Feather stars and sea lilies", code: "CWD" },
  { name: "Mola rock crab", code: "CWE" },
  { name: "Prussian carp", code: "CWG" },
  { name: "Sandwich isle filefish", code: "CWH" },
  { name: "Garish hind", code: "CWI" },
  { name: "Red snow crab", code: "CWJ" },
  { name: "Baikal yellowfin", code: "CWK" },
  { name: "Manefishes nei", code: "CWN" },
  { name: "Gulper sharks nei", code: "CWO" },
  { name: "Strawberry hind", code: "CWR" },
  { name: "Darkfin hind", code: "CWU" },
  { name: "Carcharhinus sharks nei", code: "CWZ" },
  { name: "Redfish", code: "CXF" },
  { name: "Longarm brotula", code: "CXI" },
  { name: "Blacktail snailfish", code: "CXM" },
  { name: "Sand dart", code: "CXN" },
  { name: "Red pike conger", code: "CXP" },
  { name: "Exquisite wrasse", code: "CXQ" },
  { name: "Bar jack", code: "CXR" },
  { name: "Bigeye trevally", code: "CXS" },
  { name: "Bluespotted trevally", code: "CXT" },
  { name: "Volutes nei", code: "CXY" },
  { name: "Bight redfish", code: "CXZ" },
  { name: "Smalleyed rabbitfish", code: "CYA" },
  { name: "Disc-fin squids nei", code: "CYC" },
  { name: "Philippine chimaera", code: "CYD" },
  { name: "Spotbase burrfish", code: "CYE" },
  { name: "African chimaera", code: "CYF" },
  { name: "Granular dogfish", code: "CYG" },
  { name: "Large-eyed rabbitfish", code: "CYH" },
  { name: "Bareskin dogfish", code: "CYK" },
  { name: "Black musselcracker", code: "CYM" },
  { name: "Combtooth dogfish", code: "CYN" },
  { name: "Portuguese dogfish", code: "CYO" },
  { name: "Longnose velvet dogfish", code: "CYP" },
  { name: "Whitefin dogfish", code: "CYR" },
  { name: "Blackfin ghostshark", code: "CYS" },
  { name: "Ornate dogfish", code: "CYT" },
  { name: "Plunket shark", code: "CYU" },
  { name: "Dark ghost shark", code: "CYV" },
  { name: "Roughskin dogfish", code: "CYW" },
  { name: "Shortnose velvet dogfish", code: "CYY" },
  { name: "Angel blenny", code: "CZA" },
  { name: "Prideaux's hermit crab", code: "CZB" },
  { name: "Cape Verde shearwater", code: "CZE" },
  { name: "Blue squat lobster", code: "CZJ" },
  { name: "Cherskii's sculpin", code: "CZK" },
  { name: "Right-handed hermit crabs nei", code: "CZM" },
  { name: "Bluelined hind", code: "CZO" },
  { name: "Ghost shrimps nei", code: "CZP" },
  { name: "Eastern surf chiton", code: "CZQ" },
  { name: "Spiny red gurnard", code: "CZS" },
  { name: "Ocean triggerfish", code: "CZT" },
  { name: "Duskyfin hind", code: "CZU" },
  { name: "Carcinus crabs nei", code: "CZW" },
  { name: "Caridina shrimps nei", code: "CZX" },
  { name: "Blotched snailfish", code: "CZY" },
  { name: "Maraena whitefish", code: "CZZ" },
  { name: "Hawaiian dascyllus", code: "DAA" },
  { name: "Common dab", code: "DAB" },
  { name: "Cape petrel", code: "DAC" },
  { name: "Giant danio", code: "DAE" },
  { name: "Leopard danio", code: "DAF" },
  { name: "Dagaas (=Kapenta)", code: "DAG" },
  { name: "Zebra danio", code: "DAI" },
  { name: "Amsterdam Island albatross", code: "DAM" },
  { name: "Bigeye stargazer", code: "DAO" },
  { name: "Alaska blackfish", code: "DAP" },
  { name: "Short-tailed albatross", code: "DAQ" },
  { name: "Daggerhead seabream", code: "DAR" },
  { name: "Chinese gizzard shad", code: "DAS" },
  { name: "Whitetail dascyllus", code: "DAU" },
  { name: "Sind danio", code: "DAV" },
  { name: "Round slippersnail", code: "DAW" },
  { name: "Fingered dragonet", code: "DAY" },
  { name: "European storm-petrel", code: "DAZ" },
  { name: "Banded-spine urchin", code: "DBC" },
  { name: "Spurcheek lanternfish", code: "DBE" },
  { name: "Stubby lanternfish", code: "DBF" },
  { name: "Roundnose lanternfish", code: "DBH" },
  { name: "Leach's storm-petrel", code: "DBK" },
  { name: "Double-lined mackerel", code: "DBM" },
  { name: "Tristan albatross", code: "DBN" },
  { name: "Bottlenose dolphin", code: "DBO" },
  { name: "Pawnee dragonfish", code: "DBP" },
  { name: "Pentagon star", code: "DBQ" },
  { name: "Whitespotted filefish", code: "DBS" },
  { name: "Cat's-foot star", code: "DBT" },
  { name: "Shoulderblade sea cat", code: "DBU" },
  { name: "Reticulate dascyllus", code: "DBV" },
  { name: "Dwarf swimming crab", code: "DBX" },
  { name: "Messmate pipefish", code: "DBY" },
  { name: "Indo-Pacif. bottlenose dolphin", code: "DBZ" },
  { name: "Birdbeak dogfish", code: "DCA" },
  { name: "Shortfin scad", code: "DCC" },
  { name: "Amberstripe scad", code: "DCD" },
  { name: "Rust-banded wrasse", code: "DCF" },
  { name: "Pelvic-spot wrasse", code: "DCI" },
  { name: "Threespot dascyllus", code: "DCJ" },
  { name: "Redtail scad", code: "DCK" },
  { name: "Clymene dolphin", code: "DCL" },
  { name: "Largescale wrasse", code: "DCN" },
  { name: "Common dolphin", code: "DCO" },
  { name: "Natantian decapods nei", code: "DCP" },
  { name: "Bluestripe pipefish", code: "DCQ" },
  { name: "Atlant. yellow-nosed albatross", code: "DCR" },
  { name: "Mimic crayfish", code: "DCS" },
  { name: "Roughear scad", code: "DCT" },
  { name: "Shy albatross", code: "DCU" },
  { name: "Striated wrasse", code: "DCV" },
  { name: "Diadromous clupeoids nei", code: "DCX" },
  { name: "Gabon jewelfish", code: "DCY" },
  { name: "Long-beaked common dolphin", code: "DCZ" },
  { name: "Blackspot sergeant", code: "DDA" },
  { name: "Hawaiian lionfish", code: "DDB" },
  { name: "Leaf-spiculed solenogaster", code: "DDC" },
  { name: "Indo-Pacific sergeant", code: "DDD" },
  { name: "Leaf oyster", code: "DDF" },
  { name: "Smalleye smooth-head", code: "DDH" },
  { name: "Twospot turkeyfish", code: "DDI" },
  { name: "Smalleye scabbardfish", code: "DDJ" },
  { name: "Lister's keyhole limpet", code: "DDL" },
  { name: "Sun-star", code: "DDM" },
  { name: "Frons oyster", code: "DDO" },
  { name: "Common pike conger", code: "DDP" },
  { name: "Spotted greeneye", code: "DDQ" },
  { name: "Cape chimaera", code: "DDR" },
  { name: "Porcupine sea urchin", code: "DDS" },
  { name: "Dusky dolphin", code: "DDU" },
  { name: "Kalabans", code: "DDV" },
  { name: "Great worm shell", code: "DDX" },
  { name: "Shortfin turkeyfish", code: "DDY" },
  { name: "Zebra turkeyfish", code: "DDZ" },
  { name: "Angolan dentex", code: "DEA" },
  { name: "Pennyfish", code: "DEB" },
  { name: "Common dentex", code: "DEC" },
  { name: "Leather bass", code: "DED" },
  { name: "Cuskpout", code: "DEE" },
  { name: "Stained tuskshell", code: "DEG" },
  { name: "Cloak scallop", code: "DEI" },
  { name: "Large-eye dentex", code: "DEL" },
  { name: "Morocco dentex", code: "DEM" },
  { name: "Canary dentex", code: "DEN" },
  { name: "Plain terapon", code: "DEO" },
  { name: "Pink dentex", code: "DEP" },
  { name: "Four-spotted goby", code: "DEQ" },
  { name: "Chatham Islands albatross", code: "DER" },
  { name: "Deep-sea smelt", code: "DES" },
  { name: "Lost River sucker", code: "DEU" },

  { name: "Roving coralgrouper", code: "EMU" },
  { name: "Bigspined boarfish", code: "EMV" },
  { name: "Highfin coralgrouper", code: "EMW" },
  { name: "Eucheuma seaweeds nei", code: "EMX" },
  { name: "Humming-bird bobtail squid", code: "EMY" },
  { name: "Silver cyprinid", code: "ENA" },
  { name: "Pinhead pearlfish", code: "ENB" },
  { name: "Fourbeard rockling", code: "ENC" },
  { name: "Devis' anchovy", code: "END" },
  { name: "Cape armourhead", code: "ENE" },
  { name: "Stridulating stone crab", code: "ENF" },
  { name: "Englishman seabream", code: "ENG" },
  { name: "Barred seabass", code: "ENH" },
  { name: "Orange-spotted grouper", code: "ENI" },
  { name: "Adanson's gibbula", code: "GBQ" },
  { name: "Rubberlip grunt", code: "GBR" },
  { name: "Broomtail grouper", code: "GBS" },
  { name: "Japanese blacktail triplefin", code: "GBU" },
  { name: "Upland bully", code: "GBV" },
  { name: "Divaricate gibbula", code: "GBW" },

  { name: "Bluelined wrasse", code: "SJV" },
  { name: "Broadbanded thornyhead", code: "SJW" },
  { name: "Four-spines nutshell shrimp", code: "SJX" },
  { name: "Thin birdsnest coral", code: "SJY" },
  { name: "Longspine thornyhead", code: "SJZ" },
  { name: "Raja rays nei", code: "SKA" },
  { name: "Sticklebacks", code: "SKB" },
  { name: "Caribbean monk seal", code: "SKC" },
  { name: "Sackfish", code: "SKD" },
  { name: "Comb shrimp", code: "SKE" },
  { name: "African mud shrimp", code: "SKF" },
  { name: "Various sharks nei", code: "SKH" },
  { name: "Skipjack tuna", code: "SKJ" },
  { name: "Ridgeback shrimp", code: "SKK" },
  { name: "Rough leatherjackets", code: "SKL" },
  { name: "Atlantic mud shrimp", code: "SKM" },
  { name: "Stokell's smelt", code: "SKN" },
  { name: "Chinese mud shrimp", code: "SKO" },
  { name: "Australia mus shrimp", code: "SKQ" },
  { name: "Spotfin dragonet", code: "SKS" },
  { name: "Small-headed grunter", code: "SKV" },
  { name: "Malayan mud shrimp", code: "SKW" },

  { name: "Southern rough shrimp", code: "TRV" },
  { name: "Dusky rockcod", code: "TRW" },
  { name: "Ribbonfishes", code: "TRX" },
  { name: "Yellowstripe scad", code: "TRY" },
  { name: "White trevally", code: "TRZ" },
  { name: "Little pineapple fish", code: "TSA" },
  { name: "Frail gourami", code: "TSB" },
  { name: "Twaite shad", code: "TSD" },
  { name: "Trochus shells nei", code: "TSH" },
  { name: "Threadtail anthias", code: "TSI" },
  { name: "Caribbean flounder", code: "TSJ" },
  { name: "Flapnose houndshark", code: "TSK" },
  { name: "Arabian fangblenny", code: "TSL" },
  { name: "Longfin dragonfish", code: "TSM" },
  { name: "G\u00fcnther's waspfish", code: "TSN" },
  { name: "Blunthead puffer", code: "TSP" },
  { name: "Wellington flying squid", code: "TSQ" },
  { name: "Oval grouper", code: "TSR" },
  { name: "Lionhead cichlid", code: "TSS" },
  { name: "Sickle pomfret", code: "TST" },
  { name: "Roughsnout grenadier", code: "TSU" },
  { name: "Strap-toothed whale", code: "TSW" },
  { name: "Fat horse clam", code: "TSX" },
  { name: "Lorentz catfish", code: "TSY" },
  { name: "Sharpfin houndshark", code: "TTA" },
  { name: "Rosette torpedo", code: "TTB" },
  { name: "Pacific electric ray", code: "TTC" },
  { name: "Peruvian torpedo", code: "TTD" },
  { name: "Sharptooth houndshark", code: "TTE" },
  { name: "New Zealand torpedo", code: "TTF" },
  { name: "Hawksbill turtle", code: "TTH" },
  { name: "Shorttail torpedo", code: "TTI" },
  { name: "Variable torpedo ray", code: "TTJ" },
  { name: "Bigeye notothen", code: "TTK" },
  { name: "Loggerhead turtle", code: "TTL" },
  { name: "Spotted houndshark", code: "TTM" },
  { name: "Ringed torpedo", code: "TTN" },
  { name: "Electric ray", code: "TTO" },
  { name: "Australian numbfish", code: "TTP" },
  { name: "Trapezoid torpedo", code: "TTQ" },
  { name: "Marbled electric ray", code: "TTR" },
  { name: "Chinese softshell turtle", code: "TTS" },
  { name: "Panther electric ray", code: "TTT" },
  { name: "Black-spotted torpedo", code: "TTU" },
  { name: "Common torpedo", code: "TTV" },
  { name: "Chilean torpedo", code: "TTW" },
  { name: "Marine turtles nei", code: "TTX" },
  { name: "Banded houndshark", code: "TTY" },
  { name: "Tucuxi", code: "TUC" },
  { name: "African scad", code: "TUD" },
  { name: "Steel pompano", code: "TUE" },
  { name: "Green turtle", code: "TUG" },
  { name: "Gafftopsail pompano", code: "TUH" },
  { name: "Arabian scad", code: "TUJ" },
  { name: "Indian pompano", code: "TUK" },
  { name: "River and lake turtles nei", code: "TUL" },
  { name: "Yellowtail scad", code: "TUM" },
  { name: "Tunas nei", code: "TUN" },
  { name: "Ambon rockskipper", code: "TUO" },
  { name: "Cleftbelly trevally", code: "TUP" },
  { name: "Turbot", code: "TUR" },
  { name: "True tunas nei", code: "TUS" },
  { name: "Tasmanian ruffe", code: "TUT" },
  { name: "Palmate octopus", code: "TUV" },
  { name: "Chilean semele", code: "TUW" },
  { name: "Tuna-like fishes nei", code: "TUX" },
  { name: "Yellowtail horse mackerel", code: "TUZ" },
  { name: "Common tern", code: "TVA" },
  { name: "Byron tivela", code: "TVB" },
  { name: "Candiru", code: "TVC" },
  { name: "Spotted fanfish", code: "TVE" },
  { name: "Arctic tern", code: "TVF" },
  { name: "Grey heron", code: "TVH" },
  { name: "Hairfin smooth-head", code: "TVI" },
  { name: "Hians tivela", code: "TVL" },
  { name: "Triangular tivela", code: "TVM" },
  { name: "Tanaidaceans", code: "TVN" },
  { name: "Longtail slickhead", code: "TVO" },
  { name: "Flat tivela", code: "TVP" },
  { name: "Threadfin smooth-head", code: "TVQ" },
  { name: "Triple venus", code: "TVR" },
  { name: "Distorted mussel", code: "TVS" },
  { name: "Pismo clam", code: "TVT" },
  { name: "Smooth shrimp", code: "TVU" },
  { name: "Ventricose tivela", code: "TVV" },
  { name: "Tivelas nei", code: "TVW" },
  { name: "Flathead lobsters nei", code: "TVX" },
  { name: "Philippines rough shrimp", code: "TVZ" },
  { name: "Yellowtail sardinella", code: "TWA" },
  { name: "Phaeton dragonet", code: "TWB" },
  { name: "White-capped albatross", code: "TWD" },
  { name: "Gay's little venus", code: "TWG" },
  { name: "Peruvian pelican", code: "TWH" },
  { name: "Chubby sun-star", code: "TWI" },
  { name: "Slender ribbonfish", code: "TWK" },
  { name: "Tellins nei", code: "TWL" },
  { name: "Atlantic cranch squid", code: "TWM" },
  { name: "Longtail shad", code: "TWN" },
  { name: "Moon wrasse", code: "TWO" },
  { name: "Antarctic knobbed octopus", code: "TWP" },
  { name: "Madamango sea catfish", code: "TWS" },
  { name: "Turquet's octopus", code: "TWT" },
  { name: "Sea egg", code: "TWV" },
  { name: "Patinga, hybrid", code: "TXB" },
  { name: "Spotted archerfish", code: "TXC" },
  { name: "Telescope snail", code: "TXE" },
  { name: "Hyaline tellin", code: "TXH" },
  { name: "Blackspot climbing perch", code: "TXI" },
  { name: "Banded archerfish", code: "TXJ" },
  { name: "Tiger pufferfish", code: "TXK" },
  { name: "Smallscale archerfish", code: "TXM" },
  { name: "Jordan's damsel", code: "TXO" },
  { name: "Talona pholaad", code: "TXP" },
  { name: "Senegambian tellin", code: "TXS" },
  { name: "Thin tellin", code: "TXT" },
  { name: "Pufferfishes nei", code: "TXV" },
  { name: "Blacktip tripodfish", code: "TXW" },
  { name: "Wing oysters nei", code: "TXX" },

  { name: "Biwa pearl mussel", code: "ZSU" },
  { name: "Furbellow", code: "ZSY" },
  { name: "Tinsel squirrelfish", code: "ZSZ" },
  { name: "Far Eastern ide", code: "ZTB" },
  { name: "Ribbed sculpin", code: "ZTG" },
  { name: "Peacock cranch squid", code: "ZTP" },
  { name: "Scalloped ribbonfish", code: "ZUC" },
  { name: "Taper-tail ribbonfish", code: "ZUE" },
  { name: "Russian hat sponge", code: "ZVP" },
  { name: "Common decorator crab", code: "ZYA" },
  { name: "Twospot astyanax", code: "ZYB" },
  { name: "Pronghorn decorator crab", code: "ZYD" },
  { name: "Delicate scallop", code: "ZYE" },
  { name: "Patagonian scallop", code: "ZYP" },
  { name: "Dark-mouth chimaera", code: "ZZC" },
  { name: "Falkor chimaera", code: "ZZD" },
  { name: "Seafarer\u2019s ghost shark", code: "ZZE" },
];

function SpeciesDropdown({ formControl, registerName, attrName, index }) {
  return (
    <Dropdown
      options={species}
      formControl={formControl}
      attrName={attrName}
      index={index}
      registerName={registerName}
    />
  );
}

export default SpeciesDropdown;
